const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const WORK_DIR = __dirname;
const SOL_FILE = path.join(WORK_DIR, 'ModaMintToken.sol');
const source = fs.readFileSync(SOL_FILE, 'utf8');

const input = {
  language: 'Solidity',
  sources: {
    'ModaMintToken.sol': {
      content: source
    }
  },
  settings: {
    optimizer: {
      enabled: true,
      runs: 200
    },
    viaIR: true,
    evmVersion: 'paris',
    outputSelection: {
      '*': {
        '*': ['abi', 'evm.bytecode.object', 'evm.deployedBytecode.object']
      }
    }
  }
};

console.log('编译中，使用 solc 0.8.35 + viaIR...');

// 将 input JSON 通过 stdin 传给 solc
const tmpInput = path.join(WORK_DIR, 'stdin_input.json');
fs.writeFileSync(tmpInput, JSON.stringify(input), 'utf8');

// 用 npx solc --standard-json，通过 stdin 传入
// 关键：solc 会把警告打到 stdout，需要过滤出纯 JSON 部分
try {
  const result = execSync(
    `npx solc@0.8.35 --standard-json < "${tmpInput}"`,
    {
      cwd: WORK_DIR,
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe'],
      maxBuffer: 10 * 1024 * 1024 // 10MB
    }
  );

  // solc 可能把警告混在 stdout 里，找到第一个 '{' 或 '[' 开始解析
  const stdout = result.stdout || result;
  const jsonStart = stdout.indexOf('{');
  const jsonStart2 = stdout.indexOf('[');
  let startPos;
  if (jsonStart === -1 && jsonStart2 === -1) {
    console.error('输出中没有找到 JSON：', stdout.slice(0, 500));
    process.exit(1);
  }
  if (jsonStart === -1) startPos = jsonStart2;
  else if (jsonStart2 === -1) startPos = jsonStart;
  else startPos = Math.min(jsonStart, jsonStart2);

  const jsonStr = stdout.slice(startPos);
  let output;
  try {
    output = JSON.parse(jsonStr);
  } catch (e) {
    // 如果截断导致解析失败，尝试找最后一个 '}' 配对
    console.error('JSON 解析失败，尝试修复...');
    // 找到最后一个完整的 } 位置
    let depth = 0;
    let lastGood = -1;
    for (let i = 0; i < jsonStr.length; i++) {
      if (jsonStr[i] === '{') depth++;
      if (jsonStr[i] === '}') {
        depth--;
        if (depth === 0) lastGood = i;
      }
    }
    if (lastGood > 0) {
      output = JSON.parse(jsonStr.slice(0, lastGood + 1));
    } else {
      throw e;
    }
  }

  // 检查错误
  if (output.errors) {
    const errors = output.errors.filter(e => e.severity === 'error');
    if (errors.length > 0) {
      console.error('\n❌ 编译错误:');
      errors.forEach(e => console.error(e.formattedMessage || JSON.stringify(e)));
      process.exit(1);
    }
    const warnings = output.errors.filter(e => e.severity === 'warning');
    if (warnings.length > 0) {
      console.log(`⚠️  编译警告数: ${warnings.length}（不影响编译）`);
    }
  }

  const contract = output.contracts['ModaMintToken.sol']['ModaMintToken'];
  const abi = contract.abi;
  const bytecode = '0x' + contract.evm.bytecode.object;
  const deployedBytecode = '0x' + contract.evm.deployedBytecode.object;

  console.log('\n✅ 编译成功！');
  console.log('字节码长度:', bytecode.length);
  console.log('部署字节码长度:', deployedBytecode.length);

  // 生成 contract_data.js
  const contractDataJS = `// Auto-generated by compile_v3.js — solc 0.8.35
// viaIR=true, optimizer=200 runs, evmVersion=paris
// DO NOT EDIT MANUALLY

const CONTRACT_DATA = ${JSON.stringify({ ABI: abi, BYTECODE: bytecode, DEPLOYED_BYTECODE: deployedBytecode }, null, 2)};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { CONTRACT_DATA };
}
`;

  const outputFile = path.join(WORK_DIR, 'contract_data.js');
  fs.writeFileSync(outputFile, contractDataJS, 'utf8');
  console.log('\n✅ contract_data.js 已生成:', outputFile);

  // 生成 verify_standard_input.json
  const verifyInput = {
    language: 'Solidity',
    sources: {
      'ModaMintToken.sol': {
        content: source
      }
    },
    settings: {
      optimizer: {
        enabled: true,
        runs: 200
      },
      viaIR: true,
      evmVersion: 'paris'
    }
  };

  const verifyFile = path.join(WORK_DIR, 'verify_standard_input.json');
  fs.writeFileSync(verifyFile, JSON.stringify(verifyInput, null, 2), 'utf8');
  console.log('✅ verify_standard_input.json 已生成:', verifyFile);
  console.log('\n=== 完成 ===');
  console.log('部署后用 BscScan 的 Standard-Json-Input 验证。');

} catch (e) {
  console.error('编译过程出错:', e.message);
  if (e.stdout) console.error('stdout:', e.stdout.slice(0, 1000));
  if (e.stderr) console.error('stderr:', e.stderr.slice(0, 1000));
  process.exit(1);
}
